# Generated by Django 3.2 on 2021-05-26 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('News', '0002_auto_20210525_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'verbose_name_plural': 'BookMarks'},
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.news'),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
